from openai import OpenAI
import streamlit as st
import st_yled
import json
import time

client = OpenAI(
    api_key = st.secrets["OPENAI_API_KEY"]
)
st_yled.init()
with st_yled.container(
    background_color="#6E2121",
    border_color="#dee2e6",
    padding="20px"
):    
    st_yled.title("Dungeon Crawler", color = "#FF0000")

    st_yled.subheader("This creates a situation and uses ChatGPT to choose a decision.", color = "#FF0000")

    tab1, tab2 = st_yled.tabs(["Settings", "Display"], color = "#FF0000")

    with tab1:
        with st_yled.form("Heyyyy"):
            if "name" not in st.session_state:
                st.session_state.name = ""

            st.session_state.name = st_yled.text_input("What would you like your Character's Name to be?", color = "#0000FF")

            if "persona" not in st.session_state:
                st.session_state.name = ""

            st.session_state.persona = st_yled.text_input("What fictional character do you want ChatGPT to act like:", color = "#0000FF")

            if "length" not in st.session_state:
                st.session_state.length = ""

            
            le = st_yled.number_input("How many options would you like ChatGPT to respond to and generate?", color = "#0000FF")

            st.session_state.length = le - 1
            
            button = st.form_submit_button("Confirm and Start Simulation")

        if "person_prompt" not in st.session_state:
            st.session_state.person_prompt = ""

        st.session_state.person_prompt = f"""

        You are {st.session_state.persona}.

        Your task is to choose between choices 1, 2, and 3.
        The user will input the three numbered choices, and you will choice one according to who you are's personality.
        ONLY OUTPUT 1, 2, OR 3
        """

        if "system_prompt" not in st.session_state:
            st.session_state.system_prompt = ""

        st.session_state.system_prompt = f"""
        You are a Game Master, generating a continuous campaign for the player.

        Your task is to generate VALID JSON describing a situation and 3 choices for the player.

        STRICT OUTPUT RULES:
        - Output ONLY valid JSON.
        - Do NOT include explanations, markdown, backticks, or extra text.
        - The JSON MUST be parseable by Python's json.loads().
        - The top-level structure MUST be a JSON array.
        - Do NOT add or remove keys.
        - Do NOT rename keys.
        - Fill in all empty string values with appropriate content.
        - Anything proceeded with a hashtag should NOT be included in the JSON structure, simply taken into account as a note.
        - Keep it SCHOOL APPROPRIATE.
        - The "fight" key is a boolean 
        - Use the player's name, {st.session_state.name}

        REQUIRED JSON STRUCTURE (FOLLOW EXACTLY BUT REPLACE THE PARENTHESIS WITH BRACKETS):

        [
            (
            "fight" : "",
            "situation" : "",
            "choices" : (
            "choice_1" : "",
            "choice_2" : "",
            "choice_3" : ""
                        ) 
            )
        ]

        REMEMBER:
        - Return ONLY the JSON array.
        - No surrounding text.
        """
        #Took this from a previous thing, was generated by Gpt

    if le % 1 == 0:
        with tab2:
            if button == True:    
                if "chat_history_A" not in st.session_state:
                    st.session_state.chat_history_A = ""

                st.session_state.chat_history_A = [
                {"role": "system", "content": st.session_state.system_prompt},
                {"role": "user", "content": "What's my first situation and three choices?"}
                ]

                response_A = client.chat.completions.create(
                    model="gpt-4o",
                    messages=st.session_state.chat_history_A
                )

                message_A = response_A.choices[0].message.content
                st.session_state.chat_history_A.append({"role": "assistant", "content": message_A})

                #Used GPT to debug a part where the JSON was apparently outputting as a string and added this ↓↓↓
                data = json.loads(message_A)
                with st_yled.container(
                    background_color="#4364B29E",
                    border_color="#dee2e6",
                    padding="20px"
                ):    
                    for item in data:
                        st.write("Fight:")
                        st.write(item["fight"])
                        st.write("What's happening:", item["situation"])
                        st.write("1.", item["choices"]["choice_1"] + "\n" + "2.", item["choices"]["choice_2"] + "\n" + "3.", item["choices"]["choice_3"])

                if "chat_history_B" not in st.session_state:
                    st.session_state.chat_history_B = ""

                st.session_state.chat_history_B = [
                {"role": "system", "content": st.session_state.person_prompt},
                {"role": "user", "content": f"1. {item['choices']['choice_1']}, 2. {item['choices']['choice_2']}, 3. {item['choices']['choice_3']} "}
                ]

                response_B = client.chat.completions.create(
                    model="gpt-4o",
                    messages=st.session_state.chat_history_B
                )

                message_B = response_B.choices[0].message.content
                st.session_state.chat_history_B.append({"role": "assistant", "content": message_A})
                for i in range(int(st.session_state.length)):
                    #print(message_B)

                    choice = message_B
                    valid = ["1", "2", "3"]
                    if choice in valid:
                        choiced = data[0]["choices"]["choice_" + choice]
                        st.session_state.chat_history_A.append({
                            "role": "system", "content": st.session_state.system_prompt,
                            "role": "user", "content": "I wanna " + choiced + "."
                        })
                        response_A = client.chat.completions.create(
                            model="gpt-4o",
                            messages=st.session_state.chat_history_A
                        )
                        message_A = response_A.choices[0].message.content
                        st.session_state.chat_history_A.append({"role": "assistant", "content": message_A})
                        data = json.loads(message_A)
                        with st_yled.container(
                            background_color="#5DAAB1",
                            border_color="#dee2e6",
                            padding="20px"
                        ):    
                            for item in data:
                                st.write("\n\nFight:", item["fight"])
                                st.write("What's happening:", item["situation"])
                                st.write("1.", item["choices"]["choice_1"] + "\n" + "2.", item["choices"]["choice_2"] + "\n" +"3.", item["choices"]["choice_3"])
                        st.session_state.chat_history_B = [
                        {"role": "system", "content": st.session_state.person_prompt},
                        {"role": "user", "content": f"1. {item['choices']['choice_1']}, 2. {item['choices']['choice_2']}, 3. {item['choices']['choice_3']} "}
                        ]

                        response_B = client.chat.completions.create(
                            model="gpt-4o",
                            messages=st.session_state.chat_history_B
                        )

                        message_B = response_B.choices[0].message.content
                        st.session_state.chat_history_B.append({"role": "assistant", "content": message_A})

                        st.write(message_B)
                    else:
                        print("You might be saying, 'WORK YOU COMPUTER!!!' but what I'm thinking is, 'What is bro doin with his life?'")
